Fix “connot” typos

diff --git a/libexec/sbtenv b/libexec/sbtenv
--- a/libexec/sbtenv
+++ b/libexec/sbtenv
@@ -21,7 +21,7 @@ fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "${READLINK}" ]; then
-  echo "sbtenv: connot find readlink - are you missing GNU coreutils?" >& 2
+  echo "sbtenv: cannot find readlink - are you missing GNU coreutils?" >& 2
   exit 1
 fi
 
@@ -56,7 +56,7 @@ if [ -z "${SBTENV_DIR}" ]; then
   SBTENV_DIR="$(pwd)"
 else
   cd "${SBTENV_DIR}" 2> /dev/null || {
-    echo "sbtenv: connot change working directory to \"${SBTENV_DIR}\""
+    echo "sbtenv: cannot change working directory to \"${SBTENV_DIR}\""
     exit 1
   } >& 2
   SBTENV_DIR="$(pwd)"
diff --git a/libexec/sbtenv-init b/libexec/sbtenv-init
--- a/libexec/sbtenv-init
+++ b/libexec/sbtenv-init
@@ -28,7 +28,7 @@ fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "${READLINK}" ]; then
-  echo "sbtenv: connot find readlink - are you missing GNU coreutils?" >& 2
+  echo "sbtenv: cannot find readlink - are you missing GNU coreutils?" >& 2
   exit 1
 fi
 
diff --git a/plugins/sbt-install/bin/sbtenv-install b/plugins/sbt-install/bin/sbtenv-install
--- a/plugins/sbt-install/bin/sbtenv-install
+++ b/plugins/sbt-install/bin/sbtenv-install
@@ -10,7 +10,7 @@ fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "${READLINK}" ]; then
-  echo "sbt-install: connot find readlink - are you missing GNU coreutils?" >& 2
+  echo "sbt-install: cannot find readlink - are you missing GNU coreutils?" >& 2
   exit 1
 fi
 
@@ -34,7 +34,7 @@ abs_dirname() {
 
 SHA1SUM=$(type -p sha1sum shasum | head -1)
 if [ -z "${SHA1SUM}" ]; then
-  echo "sbt-install: connot find sha1sum - are you missing GNU coreutils?" >& 2
+  echo "sbt-install: cannot find sha1sum - are you missing GNU coreutils?" >& 2
   exit 1
 fi
 
